FROM --platform=$BUILDPLATFORM ubuntu:latest AS sass-provider
WORKDIR /tmp/
# This version can be updated from time to time. Check https://github.com/sass/dart-sass/releases for the newest release.
ENV DART_SASS_VERSION=1.105.0
ADD --unpack=false https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz sass.tar.gz
RUN tar -xvzf sass.tar.gz

FROM --platform=$BUILDPLATFORM ubuntu:latest AS epubcheck-provider
RUN apt-get update && \
    apt-get install -y --no-install-recommends unzip && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /tmp/
# This version can be updated from time to time. Check https://github.com/w3c/epubcheck/releases for the newest release.
ENV EPUBCHECK_VERSION=5.4.0
ADD --unpack=false https://github.com/w3c/epubcheck/releases/download/v${EPUBCHECK_VERSION}/epubcheck-${EPUBCHECK_VERSION}.zip epubcheck.zip
RUN unzip epubcheck.zip
RUN mv epubcheck-* epubcheck

FROM --platform=$TARGETPLATFORM ubuntu:latest
RUN apt-get update && \
    apt-get install -y --no-install-recommends asciidoctor curl epubcheck git nodejs npm openjdk-21-jre pandoc tree liblouis-bin liblouis-data python3 && \
    rm -rf /var/lib/apt/lists/*
RUN gem install asciidoctor-pdf asciidoctor-epub3 asciidoctor-reducer asciimath kramdown-asciidoc
RUN npm i --global downdoc
COPY --from=sass-provider /tmp/dart-sass/ /usr/local/sbin/

WORKDIR /free5e

COPY --from=epubcheck-provider /tmp/epubcheck epubcheck
