FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y asciidoctor bash nodejs npm pandoc weasyprint tree && \
    rm -rf /var/lib/apt/lists/*
RUN gem install asciidoctor-pdf asciidoctor-epub3 asciidoctor-reducer asciimath kramdown-asciidoc
RUN npm i --global downdoc
